server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#devtools:
#  restart:
#    enabled: true
#    additional-paths: src/main/java
#    exclude: static/**,tempates/**
spring:
  redis:
    database: 0
    password: 123456
    port: 6379
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
      timeout: 1000           # 连接超时时间（毫秒）
    host: localhost
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/special_work_exam?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 10
      min-idle: 10
      max-active: 100
      min-evictable-idle-time-millis: 1800000
      max-wait: 50000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-connect-error-millis: 60000
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
pagehelper:
  helper-dialect: mysql
  default-count: true
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
swagger:

  title: 特种作业考试管理系统
  description: 特种作业考试管理系统API接口文档
  base-package: com.group.special_work_exam
  version: 0.8
  license: No license for use
  contact:
    name: 赵波
    email: 173849495@qq.com

